### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Puyodead1** [acassio/vscode-json-case-converter#1]
I'm trying to convert camelcase to snakecase but its throwing this error
```
[error] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at convertKeys (c:\Users\23562\.vscode\extensions\acassiomarques.json-to-from-camelcase-snake-case-0.0.1\out\extension.js:67:12)
    at c:\Users\23562\.vscode\extensions\acassiomarques.json-to-from-camelcase-snake-case-0.0.1\out\extension.js:15:9
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:200476)
    at h.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:201336)
    at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
    at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
    at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4762)
    at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
    at n.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
    at l.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
    at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
    at n.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
    at l.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
    at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
    at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
    at MessagePortMain.emit (node:events:514:28)
    at MessagePortMain.emit (node:domain:488:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) json-to-from-camelcase-snake-case.to_snake_case {"value":"AcassioMarques.json-to-from-camelcase-snake-case","_lower":"acassiomarques.json-to-from-camelcase-snake-case"}
```

**Comment by Puyodead1** [comment]
actually this is my mistake, i was trying to convert a json object
